name: log_utils_plus
description: "A configurable Flutter logging utility built on top of logger."
version: 1.1.0
homepage: https://github.com/akumaCN/log_utils
repository: https://github.com/akumaCN/log_utils

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
